// PRODUCT_LIST actionTypes
export const PRODUCT_LIST_WAITING = "PRODUCT_LIST_WAITING"
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_ERROR = "PRODUCT_LIST_ERROR"

// PRODUCT_DETAILS actionsTypes
export const PRODUCT_DETAILS_WAITING = "PRODUCT_DETAILS_WAITING"
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_ERROR = "PRODUCT_DETAILS_ERROR"

// CART actionTypes
export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM"

