export const PRODUCT_LIST_WAITING = "PRODUCT_LIST_WAITING"
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_ERROR = "PRODUCT_LIST_ERROR"

export const PRODUCT_DETAILS_WAITING = "PRODUCT_DETAILS_WAITING"
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_ERROR = "PRODUCT_DETAILS_ERROR"

